/**
 * Rewrites the committed model catalog from models.dev and the AI Gateway.
 *
 * The catalog is committed rather than fetched at runtime, so a board
 * that cannot reach the internet still has a list, and a fetch that
 * fails leaves the last good snapshot in place. Run this and ship the
 * diff when that fallback should move: `pnpm models:update`. The server
 * also refetches both sources once a day and serves the result without
 * a deploy. Each run rewrites the snapshot wholesale, which is also how
 * a model a provider has sunset drops out of the fallback.
 *
 * Only providers whose credentials Bento can actually store are
 * included. Offering a model that no stored key can authenticate would
 * be a dropdown entry that always fails at run time.
 *
 * Usage: pnpm models:update
 *        pnpm models:update -- --gateway-only
 */
import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import {
  CATALOG_INCLUDE,
  GATEWAY_MODELS_API,
  MODELS_DEV_API,
  buildGatewayCatalog,
  buildModelsDevCatalog,
  modelsDevLogoUrl,
  type GatewayModel,
  type ModelsDevProvider,
} from "../packages/core/src/model-catalog-build.ts";

const gatewayOnly = process.argv.includes("--gateway-only");
const root = path.join(path.dirname(fileURLToPath(import.meta.url)), "..");
const out = path.join(root, "packages/core/src/model-catalog.generated.ts");
const gatewayOut = path.join(root, "packages/core/src/model-catalog.gateway.ts");

void main().catch((err: unknown) => {
  console.error(err);
  process.exit(1);
});

async function main(): Promise<void> {
  if (!gatewayOnly) {
    const res = await fetch(MODELS_DEV_API);
    if (!res.ok) throw new Error(`models.dev returned ${res.status}`);
    const api = (await res.json()) as Record<string, ModelsDevProvider>;
    const logos: Record<string, string> = {};
    for (const id of CATALOG_INCLUDE) {
      if (!api[id]) continue;
      const logoRes = await fetch(modelsDevLogoUrl(id));
      if (!logoRes.ok) continue;
      const svg = Buffer.from(await logoRes.arrayBuffer());
      logos[id] = `data:image/svg+xml;base64,${svg.toString("base64")}`;
    }
    const built = buildModelsDevCatalog(api, logos);
    for (const warning of built.warnings) console.warn(warning);
    if (!built.ok) throw new Error(built.reason);
    for (const provider of built.providers) {
      const priced = provider.models.filter((model) => model.cost).length;
      console.log(`${provider.id}: ${provider.models.length} models, ${priced} priced${provider.logo ? "" : ", no logo"}`);
    }
    const today = new Date().toISOString().slice(0, 10);
    const body = `// Generated by scripts/update-models.ts from ${MODELS_DEV_API}
// Snapshot taken ${today}. Do not edit by hand: run \`pnpm models:update\`.
// Composer and other ids models.dev does not carry live in model-catalog.manual.ts.
import type { CatalogProvider } from "./models.js";

export const MODEL_CATALOG: readonly CatalogProvider[] = ${JSON.stringify(built.providers, null, 2)};
`;
    await writeIfChanged(out, body);
  }

  await writeGatewayCatalog();
}

async function writeGatewayCatalog(): Promise<void> {
  const res = await fetch(GATEWAY_MODELS_API);
  if (!res.ok) throw new Error(`AI Gateway returned ${res.status}`);
  const payload = (await res.json()) as { data?: GatewayModel[] };
  const built = buildGatewayCatalog(payload);
  for (const warning of built.warnings) console.warn(warning);
  if (!built.ok) throw new Error(built.reason);
  console.log(`vercel: ${built.providers[0]?.models.length ?? 0} language models`);
  const today = new Date().toISOString().slice(0, 10);
  const body = `// Generated by scripts/update-models.ts from ${GATEWAY_MODELS_API}
// Snapshot taken ${today}. Do not edit by hand: run \`pnpm models:update\`.
// Language models only. Image, video, and embedding ids stay out.
import type { CatalogProvider } from "./models.js";

export const GATEWAY_CATALOG: readonly CatalogProvider[] = ${JSON.stringify(built.providers, null, 2)};
`;
  await writeIfChanged(gatewayOut, body);
}

/**
 * Writes a snapshot only when its models changed. The header carries
 * the date it was taken, so rewriting an unchanged list would still
 * leave a diff that is nothing but the date.
 */
async function writeIfChanged(file: string, body: string): Promise<void> {
  const withoutDate = (text: string) => text.replace(/^\/\/ Snapshot taken .*$/m, "");
  const current = await readFile(file, "utf8").catch(() => "");
  const name = path.relative(root, file);
  if (withoutDate(current) === withoutDate(body)) {
    console.log(`${name} is already current`);
    return;
  }
  await writeFile(file, body);
  console.log(`wrote ${name} (${(body.length / 1024).toFixed(0)} KB)`);
}
