#!/usr/bin/env node
/**
 * Refreshes the model catalog from models.dev.
 *
 * The catalog is committed rather than fetched at runtime: a board that
 * cannot reach the internet still has to offer a model list, and a
 * dropdown whose contents change under you between sessions is worse
 * than one that changes when someone runs this script.
 *
 * Only providers whose credentials Bento can actually store are
 * included. Offering a model that no stored key can authenticate would
 * be a dropdown entry that always fails at run time.
 *
 * This writes the whole file, so it is not the place to add a provider
 * models.dev does not describe. Those live in model-catalog.manual.ts,
 * which is merged with this one in models.ts and is left alone here.
 *
 * Usage: pnpm models:update
 */
import { writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const API = "https://models.dev/api.json";
const LOGO = (id) => `https://models.dev/logos/${id}.svg`;

/** Providers we hold a credential for. See AGENT_CREDENTIALS in core. */
const INCLUDE = ["anthropic", "openai", "google", "openrouter"];

/**
 * Models to lift to the top of a provider's list.
 *
 * OpenRouter's auto router picks a model per request, which is the entry
 * most people want first and the one alphabetical order buries deepest.
 */
const PINNED = { openrouter: ["openrouter/auto"] };

const root = path.join(path.dirname(fileURLToPath(import.meta.url)), "..");
const out = path.join(root, "packages/core/src/model-catalog.generated.ts");

const res = await fetch(API);
if (!res.ok) throw new Error(`models.dev returned ${res.status}`);
const api = await res.json();

const providers = [];
for (const id of INCLUDE) {
  const provider = api[id];
  if (!provider) {
    console.warn(`skipping ${id}: not in the models.dev catalog`);
    continue;
  }
  const pinned = PINNED[id] ?? [];
  const rank = (modelId) => {
    const at = pinned.indexOf(modelId);
    return at === -1 ? pinned.length : at;
  };
  const models = Object.values(provider.models ?? {})
    .map((m) => ({ id: m.id, name: m.name ?? m.id }))
    .sort((a, b) => rank(a.id) - rank(b.id) || a.id.localeCompare(b.id));
  for (const want of pinned) {
    if (!models.some((m) => m.id === want)) console.warn(`  pinned model ${want} is not in ${id}`);
  }
  if (models.length === 0) {
    console.warn(`skipping ${id}: no models listed`);
    continue;
  }

  const logoRes = await fetch(LOGO(id));
  let logo = "";
  if (logoRes.ok) {
    const svg = Buffer.from(await logoRes.arrayBuffer());
    logo = `data:image/svg+xml;base64,${svg.toString("base64")}`;
  } else {
    console.warn(`no logo for ${id} (${logoRes.status})`);
  }

  providers.push({ id, name: provider.name ?? id, env: provider.env ?? [], logo, models });
  console.log(`${id}: ${models.length} models${logo ? "" : ", no logo"}`);
}

const today = new Date().toISOString().slice(0, 10);
const body = `// Generated by scripts/update-models.mjs from ${API}
// Snapshot taken ${today}. Do not edit by hand: run \`pnpm models:update\`.
// Providers models.dev does not carry live in model-catalog.manual.ts.
import type { CatalogProvider } from "./models.js";

export const MODEL_CATALOG: readonly CatalogProvider[] = ${JSON.stringify(providers, null, 2)};
`;

await writeFile(out, body);
console.log(`\nwrote ${path.relative(root, out)} (${(body.length / 1024).toFixed(0)} KB)`);
